### PR TITLE
Do not require all Druxt modules

### LINKED ISSUE #13: Split out "Drupal parity" into new module.
**Is your feature request related to a problem? Please describe.**
We'd like to use druxt.js, but not all of the modules.

Currently we're forced to use them all per https://github.com/druxt/druxt.js/blob/develop/src/module.js#L30

```
  // Add NuxtJS modules.
  const modules = [
    '@nuxtjs/proxy',
    'druxt-blocks',
    'druxt-breadcrumb',
    'druxt-entity',
    'druxt-menu',
    'druxt-router',
    'druxt-schema',
    'druxt-search',
    'druxt-views'
  ]
  for (const key in modules) {
    this.addModule(modules[key])
  }
```

**Describe the solution you'd like**
I'd like druxt.js to just work with what modules we define.

**Describe alternatives you've considered**
Hacking the code in node_modules

**Additional context**
druxt-schema does not work with aliased resource types. So the alternative is to not use schema or entity modules.

### PR DESCRIPTION
**Pull request by mglaman**
Maybe this isn't the right approach. Maybe there needs to be feature flags that turn off specific modules. But this is a first approach.

Fixes #13﻿

### CODE REVIEW

**Comment by Decipher** [comment]
The only purpose of the DruxtJS module at the moment is to enable all these modules and configure some extra things. If you want to use modules individually you can already do that by not using the `druxt` module at all.

This issue requires documentation and examples rather than a code change here.

**Comment by mglaman** [comment]
Ah, we tried that and got an error about the Vuex store not existing, and I saw this package provides one

**Comment by Decipher** [comment]
> Ah, we tried that and got an error about the Vuex store not existing, and I saw this package provides one

Yes, the Vuex store does need to be setup. In the main DruxtJS module that is being done for you, but if you are using the modules individually at the moment you will need to ensure a Vuex store is present in the NuxtJS project.

The easiest way to do this is by creating the following file with the following content:

`store/index.js`
```
export default {}
```

An example of a Nuxt codebase with a single module can be see here: https://github.com/Decipher/druxt-menu-example

**Comment by mglaman** [comment]
@Decipher great! so there's nothing _too_ fancy for the store.

Maybe we can have a repo in the org for an "awesome-druxt" list and "druxt-contrib"

Totally ripping this from https://github.com/drud/awesome-ddev and https://github.com/drud/ddev-contrib.

-- 

Closing so we could solve this in the main issue.

**Comment by Decipher** [comment]
> so there's nothing _too_ fancy for the store.

Yeah, NuxtJS only initialises the Vuex store if you have atleast one module present. But the DruxtJS module specifically turns the feature on.

Each individual module that has a Vuex store should also be doing this, I will follow that up in in the future.

And absolutely intend to have `awesome-druxt`.

**Pull request closed without merging**
